version: '3'

services:

    nginx:
      image: nginx:latest
      build:
        context: ./docker/
        args:
          - "BUILD_ARGUMENT_ENV=staging"
        dockerfile: ./nginx/Dockerfile
      container_name: ${COMPOSE_PROJECT_NAME}_nginx
      restart: always
      ports:
        - 80:80
        - 443:443
      volumes:
        - .:/var/www/html:ro
      depends_on:
        - symfony
      links:
        - symfony

    symfony: &symfony-template
      image: symfony:latest
      build:
        context: .
        args:
          - "BUILD_ARGUMENT_ENV=staging"
          - "BUILD_ARGUMENT_DEBUG_ENABLED=false"
        dockerfile: ./Dockerfile
      container_name: ${COMPOSE_PROJECT_NAME}_symfony
      restart: always
      expose:
        - 9000
      depends_on:
        - mysql
        - rabbitmq
        - elasticsearch
      links:
        - mysql
        - rabbitmq
        - elasticsearch

    ### Cron tasks, RabbitMQ consumers
    supervisord:
      <<: *symfony-template
      container_name: ${COMPOSE_PROJECT_NAME}_supervisord
      expose: []
      command: ["/usr/bin/supervisord"]

    mysql:
      image: mysql:8.0
      container_name: ${COMPOSE_PROJECT_NAME}_mysql
      restart: always
      command: --default-authentication-plugin=mysql_native_password
      environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_DATABASE=symfony
      volumes:
        - ./var/mysql-data:/var/lib/mysql

    rabbitmq:
      image: rabbitmq:3-management-alpine
      build:
        context: ./docker/rabbitmq/
        dockerfile: ./Dockerfile
      container_name: ${COMPOSE_PROJECT_NAME}_rabbitmq
      restart: always
      environment:
        - RABBITMQ_ERLANG_COOKIE=7ead507151fc4461b9f45c1161384a04
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
        - RABBITMQ_DEFAULT_VHOST=/
      ports:
        - 15672:15672
      volumes:
        - ./var/rabbitmq:/var/lib/rabbitmq

    elasticsearch:
      image: elasticsearch:latest
      build:
        context: ./docker/
        args:
          - "ELK_VERSION=${ELK_VERSION}"
        dockerfile: ./elasticsearch/Dockerfile
      container_name: ${COMPOSE_PROJECT_NAME}_elasticsearch
      restart: always
      environment:
        ES_JAVA_OPTS: "-Xmx4096m -Xms4096m"
        ELASTIC_PASSWORD: changeme
        # Use single node discovery in order to disable production mode and avoid bootstrap checks
        # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
        discovery.type: single-node
      ports:
        - 9200:9200
        - 9300:9300
      volumes:
        - ./docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
        - ./var/elasticsearch-data:/usr/share/elasticsearch/data

    kibana:
      image: kibana:latest
      build:
        context: ./docker/
        args:
          - "ELK_VERSION=${ELK_VERSION}"
        dockerfile: ./kibana/Dockerfile
      container_name: ${COMPOSE_PROJECT_NAME}_kibana
      ports:
        - 5601:5601
      volumes:
        - ./docker/staging/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      depends_on:
        - elasticsearch
