api-key-controllers:
    resource: ../../src/ApiKey/Transport/Controller/Api/
    type: annotation
    prefix: /api
    defaults:
        _format: json

role-controllers:
    resource: ../../src/Role/Transport/Controller/Api/
    type: annotation
    prefix: /api
    defaults:
        _format: json

tool-controllers:
    resource: ../../src/Tool/Transport/Controller/Api/
    type: annotation
    prefix: /api
    defaults:
        _format: json

user-controllers:
    resource: ../../src/User/Transport/Controller/Api/
    type: annotation
    prefix: /api
    defaults:
        _format: json

#web-controller:
#    resource: ../../src/Controller/Web/
#    type: annotation
#    prefix: /web

kernel:
    resource: ../../src/Kernel.php
    type: annotation
