api-controller:
    resource: ../../src/Controller/Api/
    type: annotation
    prefix: /api
    defaults:
        _format: json

web-controller:
    resource: ../../src/Controller/Web/
    type: annotation
    prefix: /web

kernel:
    resource: ../../src/Kernel.php
    type: annotation
