version: 2
jobs:
  build:
    working_directory: ~/html
    machine: true
    branches:
        ignore:
          - develop
    steps:
      - checkout

      - run:
          name: Prepare and start containers and verify it's working
          command: |
            chmod 777 var/elasticsearch-data
            make start-test

      - run:
          name: Wait for DB container is running and initialize DB & messenger component / cron / elastic
          command: |
            make wait-for-db
            make drop-migrate
            make generate-jwt-keys
            make create-roles-groups
            make migrate-cron-jobs
            make messenger-setup-transports
            make wait-for-elastic
            make elastic-create-or-update-template

      - run:
          name: Run unit/functional tests
          command: |
            make phpunit

      - run:
          name: Report code coverage
          command: |
            make report-code-coverage

      - run:
          name: Check coding standard & CodeSniffer
          command: |
            make ecs
            make phpcs

      - store_artifacts:
          path: reports

      - store_test_results:
          path: reports
