api-key-controllers:
    resource: ../src/ApiKey/Transport/Controller/Api/
    type: attribute
    prefix: /api
    defaults:
        _format: json

role-controllers:
    resource: ../src/Role/Transport/Controller/Api/
    type: attribute
    prefix: /api
    defaults:
        _format: json

tool-controllers:
    resource: ../src/Tool/Transport/Controller/Api/
    type: attribute
    prefix: /api
    defaults:
        _format: json

user-controllers:
    resource: ../src/User/Transport/Controller/Api/
    type: attribute
    prefix: /api
    defaults:
        _format: json
