name: Symfony Rest API

on:
    push:
        branches:
            - master
            - develop
    pull_request:
        branches:
            - master
            - develop
    release:
        types: [published]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Set Elastic data folder rights
              run: chmod 777 var/elasticsearch-data
            - name: Build the docker images
              run: make build-test
            - name: Start the docker images
              run: make start-test
            - name: Check running containers
              run: docker ps -a
            - name: Wait for database connection
              run: make wait-for-db
            - name: Run migrations
              run: make drop-migrate
            - name: Generate keys
              run: make generate-jwt-keys
            - name: Create roles and groups
              run: make create-roles-groups
            - name: Create cron jobs
              run: make migrate-cron-jobs
            - name: Setup transports for Messenger component
              run: make messenger-setup-transports
            - name: Wait for Elastic connection
              run: make wait-for-elastic
            - name: Create or update Elastic index template
              run: make elastic-create-or-update-template
            - name: Show framework version and additional info, php & composer version
              run: make info
            - name: Run test suite
              run: make phpunit
            - name: Run coding standard
              run: make ecs
            - name: Run codeSniffer
              run: make phpcs
            - name: Run PHPStan
              run: make phpstan
            - name: Run PHPInsights
              run: make phpinsights
            - name: Run php copy past detector
              run: make phpcpd
            - name: Run php mess detector
              run: make phpmd
            - name: Stop the docker images
              run: make stop-test

    qodana:
        runs-on: ubuntu-latest
        needs: build
        permissions:
            contents: write
            pull-requests: write
            checks: write
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
                  fetch-depth: 0  # a full history is required for pull request analysis
            - name: 'Qodana Scan'
              uses: JetBrains/qodana-action@v2023.2
              env:
                  QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
